In [30]:
# ==============================================================================
# 1. INSTALAÇÃO DE DEPENDÊNCIAS (Sem conectores Java do S3)
# ==============================================================================
!pip install pyspark boto3 pandas -q


import os
import boto3
import pandas as pd
from datetime import datetime, timezone
from pyspark.sql.types import StructType, StructField, StringType, IntegerType, DoubleType, TimestampType
from pyspark.sql.window import Window
from pyspark.sql import functions as F

# ==============================================================================
# 2. INICIALIZAÇÃO DO SPARK (Simples e Leve)
# ==============================================================================
from pyspark.sql import SparkSession
from pyspark.sql import functions as F

spark = SparkSession.builder \
    .appName("Ingestao-Colab-Bronze") \
    .config("spark.sql.sources.partitionOverwriteMode", "dynamic") \
    .getOrCreate()

# ==============================================================================
# 3. CONFIGURAÇÃO DO CLIENTE AWS NATIVO (Boto3)
# ==============================================================================
AWS_ACCESS_KEY = "ASIASDRQQLLLZEEJDNJY"
AWS_SECRET_KEY = "uX6+HMUR8OuJSFBJCddSMhH1BUxKTIGy5eHc7Vne"
AWS_SESSION_TOKEN = "IQoJb3JpZ2luX2VjEHsaCXVzLXdlc3QtMiJHMEUCIC2F6GFcDswzUeqnSAGVZyWkAAtD32x7YSSvFsPjkqLvAiEAkmUcJSXAoJ9gkfxDb12zBkqMAus3eoBoL8lK3Q5vtEAqtQIIRBAAGgwxNDUwNTY4ODEzNjciDJX0uqcMvd/MeN1V6yqSAhbXKIIihRwPrlzCKbw45ydLbjHY/wUComA8QKD8PL+yoh+p5Y9U3lj2LiFDahIgMnTa2NN68ByzmkRAraqlKJYlUOUIPHcMNd7ylC0e3sLA0x3O2eVKu3QQbEHBMNSVDHxGkp0sxjyLR+2EdjfrsSqR6zqU/nYMG6ppwmnagMCTkkxnRwGfmZ4dgozG+UT2kHwHmjwJsocwIKJnYuN1C3HMfbf2CxJziK2CSAvUDzT0VCXmmBWlVRmMX/4uwyIRUl/6J6MYtsvoeorRQoa7Ec8gMhSTM0cZrV1zPTr74WE3T6BXBICRPPmdNgv7KI9X3SYnP5mP/IhaQjbNSZOjDsUuH8eJsjq/nxuNCp6khiJ+xRMw4azy0QY6nQE45ElrNguoOlJ8XFL3jjupcxiNibf8IDfcSdfGbo65tu+sXuZchYGKJBD+WN8erl27iCvfF4c6UfjY3kJo8qIUiPLkfxZqtMCedY8PLi4PRUe8KBKLlZO0IcskbzQTp1QyAzZB+eet1poqagX7pFVr9R9saG0V7tssq+21hlwVZ5BAMW39vWQaZ+pGJZNihT+G4edTJQi+800v38GY"
# Cria o cliente S3 nativo do Python (não passa pelo Java/Hadoop)
if AWS_SESSION_TOKEN and AWS_SESSION_TOKEN != "SESSION_TOKEN":
    s3_client = boto3.client(
        's3',
        aws_access_key_id=AWS_ACCESS_KEY,
        aws_secret_access_key=AWS_SECRET_KEY,
        aws_session_token=AWS_SESSION_TOKEN
    )
else:
    s3_client = boto3.client(
        's3',
        aws_access_key_id=AWS_ACCESS_KEY,
        aws_secret_access_key=AWS_SECRET_KEY
    )

# ==============================================================================
# 4. VARIÁVEIS GLOBAIS DE TEMPO E BUCKETS
# ==============================================================================
INGESTION_TS = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
INGESTION_DATE = datetime.now(timezone.utc).strftime("%Y-%m-%d")
ANOMESDIA = datetime.now(timezone.utc).strftime("%Y%m%d")

BUCKET_PRINICIPAL = "fiap-datalake-fase2"
PASTA_RAW = "raw"
PASTA_BRONZE = "bronze"
PASTA_SILVER = "silver"
PASTA_GOLD = "gold"

print("✅ Ambiente Spark + Boto3 configurado com sucesso!")

✅ Ambiente Spark + Boto3 configurado com sucesso!

In [31]:
# ==============================================================================
# CÉLULA 2: MAPEAMENTO DE SCHEMAS E ARQUIVOS REAIS DO S3
# ==============================================================================
from pyspark.sql.types import StructType, StructField, StringType, IntegerType, DoubleType, TimestampType

# Seus nomes de entidades organizadas (como vão ficar as pastas na Bronze)
ENTIDADES = [
    "meta_brasil", "meta_uf", "meta_municipio",
    "municipio", "uf", "alunos_2023", "alunos_2024", "alunos_2025"
]

# DICIONÁRIO DE DEPARA: Relaciona a entidade com o nome REAL do arquivo no S3
ARQUIVOS_MAP = {
    "meta_brasil": "br_inep_avaliacao_alfabetizacao_meta_alfabetizacao_brasil.csv",
    "meta_uf": "br_inep_avaliacao_alfabetizacao_meta_alfabetizacao_uf.csv",
    "meta_municipio": "br_inep_avaliacao_alfabetizacao_meta_alfabetizacao_municipio.csv",
    "municipio": "br_inep_avaliacao_alfabetizacao_municipio.csv",
    "uf": "br_inep_avaliacao_alfabetizacao_uf.csv",
    "alunos_2023": "TS_ALUNO_2023.csv",
    "alunos_2024": "TS_ALUNO_2024.csv",
    "alunos_2025": "TS_ALUNO_2025.csv"
}

# Dicionário de schemas
SCHEMAS_MAP = {
    "meta_brasil": StructType([
        StructField("ano", IntegerType(), True),
        StructField("rede", StringType(), True),
        StructField("taxa_alfabetizacao", DoubleType(), True),
        StructField("meta_alfabetizacao_2024", DoubleType(), True),
        StructField("meta_alfabetizacao_2025", DoubleType(), True),
        StructField("meta_alfabetizacao_2026", DoubleType(), True),
        StructField("meta_alfabetizacao_2027", DoubleType(), True),
        StructField("meta_alfabetizacao_2028", DoubleType(), True),
        StructField("meta_alfabetizacao_2029", DoubleType(), True),
        StructField("meta_alfabetizacao_2030", DoubleType(), True),
        StructField("percentual_participacao", DoubleType(), True)
    ]),
    "meta_uf": StructType([
        StructField("ano", IntegerType(), True),
        StructField("sigla_uf", StringType(), True),
        StructField("rede", StringType(), True),
        StructField("taxa_alfabetizacao", DoubleType(), True),
        StructField("meta_alfabetizacao_2024", DoubleType(), True),
        StructField("meta_alfabetizacao_2025", DoubleType(), True),
        StructField("meta_alfabetizacao_2026", DoubleType(), True),
        StructField("meta_alfabetizacao_2027", DoubleType(), True),
        StructField("meta_alfabetizacao_2028", DoubleType(), True),
        StructField("meta_alfabetizacao_2029", DoubleType(), True),
        StructField("meta_alfabetizacao_2030", DoubleType(), True),
        StructField("percentual_participacao", DoubleType(), True)
    ]),
    "meta_municipio": StructType([
        StructField("ano", IntegerType(), True),
        StructField("id_municipio", IntegerType(), True),
        StructField("rede", StringType(), True),
        StructField("taxa_alfabetizacao", DoubleType(), True),
        StructField("meta_alfabetizacao_2024", DoubleType(), True),
        StructField("meta_alfabetizacao_2025", DoubleType(), True),
        StructField("meta_alfabetizacao_2026", DoubleType(), True),
        StructField("meta_alfabetizacao_2027", DoubleType(), True),
        StructField("meta_alfabetizacao_2028", DoubleType(), True),
        StructField("meta_alfabetizacao_2029", DoubleType(), True),
        StructField("meta_alfabetizacao_2030", DoubleType(), True),
        StructField("nivel_alfabetizacao", DoubleType(), True),
        StructField("percentual_participacao", DoubleType(), True)
    ]),
    "municipio": StructType([
        StructField("ano", IntegerType(), True),
        StructField("id_municipio", IntegerType(), True),
        StructField("serie", IntegerType(), True),
        StructField("rede", IntegerType(), True),
        StructField("taxa_alfabetizacao", DoubleType(), True),
        StructField("media_portugues", DoubleType(), True),
        StructField("proporcao_aluno_nivel_0", DoubleType(), True),
        StructField("proporcao_aluno_nivel_1", DoubleType(), True),
        StructField("proporcao_aluno_nivel_2", DoubleType(), True),
        StructField("proporcao_aluno_nivel_3", DoubleType(), True),
        StructField("proporcao_aluno_nivel_4", DoubleType(), True),
        StructField("proporcao_aluno_nivel_5", DoubleType(), True),
        StructField("proporcao_aluno_nivel_6", DoubleType(), True),
        StructField("proporcao_aluno_nivel_7", DoubleType(), True),
        StructField("proporcao_aluno_nivel_8", DoubleType(), True)
    ]),
    "uf": StructType([
          StructField("ano", IntegerType(), True),
          StructField("sigla_uf", StringType(), True),
          StructField("serie", IntegerType(), True),
          StructField("rede", IntegerType(), True),
          StructField("taxa_alfabetizacao", DoubleType(), True),
          StructField("media_portugues", DoubleType(), True),
          StructField("proporcao_aluno_nivel_0", DoubleType(), True),
          StructField("proporcao_aluno_nivel_1", DoubleType(), True),
          StructField("proporcao_aluno_nivel_2", DoubleType(), True),
          StructField("proporcao_aluno_nivel_3", DoubleType(), True),
          StructField("proporcao_aluno_nivel_4", DoubleType(), True),
          StructField("proporcao_aluno_nivel_5", DoubleType(), True),
          StructField("proporcao_aluno_nivel_6", DoubleType(), True),
          StructField("proporcao_aluno_nivel_7", DoubleType(), True),
          StructField("proporcao_aluno_nivel_8", DoubleType(), True)
    ]),
    "alunos_2023": StructType([
        StructField("NU_ANO_AVALIACAO", IntegerType(), True),
        StructField("CO_UF", IntegerType(), True),
        StructField("SG_UF", StringType(), True),
        StructField("ID_ALUNO", IntegerType(), True),
        StructField("TP_SERIE", IntegerType(), True),
        StructField("ID_ESCOLA", IntegerType(), True),
        StructField("TP_DEPENDENCIA", IntegerType(), True),
        StructField("CO_MUNICIPIO", IntegerType(), True),
        StructField("NO_MUNICIPIO", StringType(), True),
        StructField("IN_PRESENCA_LP", IntegerType(), True),
        StructField("IN_PREENCHIMENTO_LP", IntegerType(), True),
        StructField("CO_CADERNO_LP", IntegerType(), True),
        StructField("VL_PESO_ALUNO_LP", DoubleType(), True),
        StructField("VL_PROFICIENCIA_LP", DoubleType(), True),
        StructField("IN_ALFABETIZADO", IntegerType(), True)
    ]),
    "alunos_2024": StructType([
        StructField("NU_ANO_AVALIACAO", IntegerType(), True),
        StructField("CO_UF", IntegerType(), True),
        StructField("SG_UF", StringType(), True),
        StructField("ID_ALUNO", IntegerType(), True),
        StructField("TP_SERIE", IntegerType(), True),
        StructField("ID_ESCOLA", IntegerType(), True),
        StructField("TP_DEPENDENCIA", IntegerType(), True),
        StructField("CO_MUNICIPIO", IntegerType(), True),
        StructField("NO_MUNICIPIO", StringType(), True),
        StructField("IN_PRESENCA_LP", IntegerType(), True),
        StructField("IN_PREENCHIMENTO_LP", IntegerType(), True),
        StructField("CO_CADERNO_LP", IntegerType(), True),
        StructField("VL_PESO_ALUNO_LP", DoubleType(), True),
        StructField("VL_PROFICIENCIA_LP", DoubleType(), True),
        StructField("IN_ALFABETIZADO", IntegerType(), True)
    ]),
    "alunos_2025": StructType([
        StructField("NU_ANO_AVALIACAO", IntegerType(), True),
        StructField("CO_UF", IntegerType(), True),
        StructField("SG_UF", StringType(), True),
        StructField("ID_ALUNO", IntegerType(), True),
        StructField("TP_SERIE", IntegerType(), True),
        StructField("ID_ESCOLA", IntegerType(), True),
        StructField("TP_DEPENDENCIA", IntegerType(), True),
        StructField("CO_MUNICIPIO", IntegerType(), True),
        StructField("NO_MUNICIPIO", StringType(), True),
        StructField("IN_PRESENCA_LP", IntegerType(), True),
        StructField("IN_PREENCHIMENTO_LP", IntegerType(), True),
        StructField("CO_CADERNO_LP", IntegerType(), True),
        StructField("VL_PESO_ALUNO_LP", DoubleType(), True),
        StructField("VL_PROFICIENCIA_LP", DoubleType(), True),
        StructField("IN_ALFABETIZADO", IntegerType(), True)
    ]),

}
print("✅ Mapeamento de arquivos físicos carregado com sucesso!")

✅ Mapeamento de arquivos físicos carregado com sucesso!

In [32]:
def fazer_upload_pasta_s3(pasta_local, bucket, prefixo_s3):
    """
    Função auxiliar para varrer a pasta local do Colab e enviar os arquivos ao S3
    """
    import os
    for raiz, diretorios, arquivos in os.walk(pasta_local):
        for arquivo in arquivos:
            caminho_completo_local = os.path.join(raiz, arquivo)
            # Calcula o caminho relativo para manter a estrutura de pastas no S3
            caminho_relativo = os.path.relpath(caminho_completo_local, pasta_local)
            key_s3 = os.path.join(prefixo_s3, caminho_relativo).replace("\\", "/")

            # Envia o arquivo para o S3 via Boto3
            s3_client.upload_file(caminho_completo_local, bucket, key_s3)

def executar_pipeline_bronze(entidade, bucket, pasta_in, pasta_out):
    """
    Lê o CSV do S3 tratando encoding e identificando o separador (, ou ;) de forma
    automática, aplica tipagem via .cast() tratando strings 'NaN'/nulas, adiciona metadados,
    grava em Parquet localmente e faz o upload dos arquivos gerados de volta para o S3.
    """
    print(f"\n--- Iniciando processamento da entidade: {entidade} ---")

    # Busca o nome real do arquivo no dicionário mapeado
    nome_arquivo_real = ARQUIVOS_MAP.get(entidade, f"{entidade}.csv")

    key_input_csv = f"{pasta_in}/{nome_arquivo_real}"

    # Define a estrutura de partições
    estrutura_destino = f"{entidade}/anomesdia={ANOMESDIA}"
    path_local_output = f"./output/{pasta_out}/{estrutura_destino}"
    key_s3_output = f"{pasta_out}/{estrutura_destino}"

    print(f"[RAW] Baixando objeto do S3 via Boto3: {key_input_csv}")

    # 1. Leitura do S3 tratando dinamicamente Encoding e Separador
    try:
        obj = s3_client.get_object(Bucket=bucket, Key=key_input_csv)
        corpo_arquivo = obj['Body'].read()

        try:
            # Tenta UTF-8 descobrindo o separador automaticamente
            pdf = pd.read_csv(pd.io.common.BytesIO(corpo_arquivo), sep=None, engine='python', encoding="utf-8", dtype=str)
        except UnicodeDecodeError:
            print(f"[AVISO] Falha ao decodificar em UTF-8 para '{entidade}'. Tentando padrão ISO-8859-1 (Latin1)...")
            # Fallback para Latin1 descobrindo o separador automaticamente
            pdf = pd.read_csv(pd.io.common.BytesIO(corpo_arquivo), sep=None, engine='python', encoding="ISO-8859-1", dtype=str)

    except Exception as e:
        print(f"[ERRO] Falha ao ler ou decodificar arquivo do S3 via Boto3: {str(e)}")
        raise e

    # 2. Captura o schema específico se existir, caso contrário lê genérico
    schema_especifico = SCHEMAS_MAP.get(entidade, None)

    # Convertendo o DataFrame do Pandas para Spark DataFrame
    if schema_especifico:
        print(f"[RAW] Schema explícito encontrado para '{entidade}'. Ajustando tipos e tratando NaNs...")

        # Cria o DataFrame temporário flexível
        df_temp = spark.createDataFrame(pdf)

        # Intercepta strings textuais nulas/NaN antes de realizar o .cast()
        expressoes_tipo = [
            F.when(F.col(campo.name).isin(["NaN", "nan", "None", "NULL", "nan"]), F.lit(None))
             .otherwise(F.col(campo.name))
             .cast(campo.dataType)
             .alias(campo.name)
            for campo in schema_especifico
        ]
        df_raw = df_temp.select(*expressoes_tipo)
    else:
        print(f"[RAW] Nenhum schema mapeado para '{entidade}'. Convertendo como texto.")
        df_raw = spark.createDataFrame(pdf)

    # 3. Adição de Metadados de Auditoria
    print("[BRONZE] Aplicando metadados de auditoria...")
    path_fake_s3 = f"s3://{bucket}/{key_input_csv}"
    df_bronze = (df_raw
        .withColumn("_ingestion_timestamp", F.lit(INGESTION_TS))
        .withColumn("_ingestion_date",      F.lit(INGESTION_DATE))
        .withColumn("_source_path",         F.lit(path_fake_s3))
        .withColumn("_source_entity",       F.lit(entidade))
        .withColumn("_environment",         F.lit("dev"))
    )

    # 4. Escrita no formato Parquet (Local no ambiente do Colab)
    print(f"[BRONZE] Salvando Parquet temporariamente no Colab...")
    df_bronze.write.mode("overwrite").parquet(path_local_output)

    # 5. Upload da estrutura Parquet gerada de volta para o S3
    print(f"[S3-UPLOAD] Enviando arquivos Parquet para o S3 em: s3://{bucket}/{key_s3_output}/")
    try:
        fazer_upload_pasta_s3(path_local_output, bucket, key_s3_output)
        print(f"[S3-UPLOAD] Upload concluído com sucesso!")
    except Exception as e:
        print(f"[ERRO] Falha ao enviar arquivos para o S3: {str(e)}")
        raise e

    print(f"[SUCESSO] Entidade '{entidade}' processada e salva no S3. Registros: {df_bronze.count()}")

In [ ]:
# Execução em loop para as tabelas
for entidade in ENTIDADES:
    try:
        executar_pipeline_bronze(
            entidade=entidade,
            bucket=BUCKET_PRINICIPAL,
            pasta_in=PASTA_RAW,
            pasta_out=PASTA_BRONZE
        )
    except Exception as e:
        print(f"[ERRO] Falha ao processar a entidade {entidade}: {str(e)}")

--- Iniciando processamento da entidade: meta_brasil ---
[RAW] Baixando objeto do S3 via Boto3: raw/br_inep_avaliacao_alfabetizacao_meta_alfabetizacao_brasil.csv
[RAW] Schema explícito encontrado para 'meta_brasil'. Ajustando tipos e tratando NaNs...
[BRONZE] Aplicando metadados de auditoria...
[BRONZE] Salvando Parquet temporariamente no Colab...
[S3-UPLOAD] Enviando arquivos Parquet para o S3 em: s3://fiap-datalake-fase2/bronze/meta_brasil/anomesdia=20260625/
[S3-UPLOAD] Upload concluído com sucesso!
[SUCESSO] Entidade 'meta_brasil' processada e salva no S3. Registros: 3

--- Iniciando processamento da entidade: meta_uf ---
[RAW] Baixando objeto do S3 via Boto3: raw/br_inep_avaliacao_alfabetizacao_meta_alfabetizacao_uf.csv
[RAW] Schema explícito encontrado para 'meta_uf'. Ajustando tipos e tratando NaNs...
[BRONZE] Aplicando metadados de auditoria...
[BRONZE] Salvando Parquet temporariamente no Colab...
[S3-UPLOAD] Enviando arquivos Parquet para o S3 em: s3://fiap-datalake-fase2/bronze/meta_uf/anomesdia=20260625/
[S3-UPLOAD] Upload concluído com sucesso!
[SUCESSO] Entidade 'meta_uf' processada e salva no S3. Registros: 54

--- Iniciando processamento da entidade: meta_municipio ---
[RAW] Baixando objeto do S3 via Boto3: raw/br_inep_avaliacao_alfabetizacao_meta_alfabetizacao_municipio.csv
[RAW] Schema explícito encontrado para 'meta_municipio'. Ajustando tipos e tratando NaNs...
[BRONZE] Aplicando metadados de auditoria...
[BRONZE] Salvando Parquet temporariamente no Colab...
[S3-UPLOAD] Enviando arquivos Parquet para o S3 em: s3://fiap-datalake-fase2/bronze/meta_municipio/anomesdia=20260625/
[S3-UPLOAD] Upload concluído com sucesso!
[SUCESSO] Entidade 'meta_municipio' processada e salva no S3. Registros: 10704

--- Iniciando processamento da entidade: municipio ---
[RAW] Baixando objeto do S3 via Boto3: raw/br_inep_avaliacao_alfabetizacao_municipio.csv
[RAW] Schema explícito encontrado para 'municipio'. Ajustando tipos e tratando NaNs...
[BRONZE] Aplicando metadados de auditoria...
[BRONZE] Salvando Parquet temporariamente no Colab...
[S3-UPLOAD] Enviando arquivos Parquet para o S3 em: s3://fiap-datalake-fase2/bronze/municipio/anomesdia=20260625/
[S3-UPLOAD] Upload concluído com sucesso!
[SUCESSO] Entidade 'municipio' processada e salva no S3. Registros: 23995

--- Iniciando processamento da entidade: uf ---
[RAW] Baixando objeto do S3 via Boto3: raw/br_inep_avaliacao_alfabetizacao_uf.csv
[RAW] Schema explícito encontrado para 'uf'. Ajustando tipos e tratando NaNs...
[BRONZE] Aplicando metadados de auditoria...
[BRONZE] Salvando Parquet temporariamente no Colab...
[S3-UPLOAD] Enviando arquivos Parquet para o S3 em: s3://fiap-datalake-fase2/bronze/uf/anomesdia=20260625/
[S3-UPLOAD] Upload concluído com sucesso!
[SUCESSO] Entidade 'uf' processada e salva no S3. Registros: 145

--- Iniciando processamento da entidade: alunos_2023 ---
[RAW] Baixando objeto do S3 via Boto3: raw/TS_ALUNO_2023.csv
[AVISO] Falha ao decodificar em UTF-8 para 'alunos_2023'. Tentando padrão ISO-8859-1 (Latin1)...
[RAW] Schema explícito encontrado para 'alunos_2023'. Ajustando tipos e tratando NaNs...
[BRONZE] Aplicando metadados de auditoria...
[BRONZE] Salvando Parquet temporariamente no Colab...
[S3-UPLOAD] Enviando arquivos Parquet para o S3 em: s3://fiap-datalake-fase2/bronze/alunos_2023/anomesdia=20260625/
[S3-UPLOAD] Upload concluído com sucesso!
[SUCESSO] Entidade 'alunos_2023' processada e salva no S3. Registros: 1747439

--- Iniciando processamento da entidade: alunos_2024 ---
[RAW] Baixando objeto do S3 via Boto3: raw/TS_ALUNO_2024.csv
[AVISO] Falha ao decodificar em UTF-8 para 'alunos_2024'. Tentando padrão ISO-8859-1 (Latin1)...
[RAW] Schema explícito encontrado para 'alunos_2024'. Ajustando tipos e tratando NaNs...
[BRONZE] Aplicando metadados de auditoria...
[BRONZE] Salvando Parquet temporariamente no Colab...
[S3-UPLOAD] Enviando arquivos Parquet para o S3 em: s3://fiap-datalake-fase2/bronze/alunos_2024/anomesdia=20260625/
[S3-UPLOAD] Upload concluído com sucesso!
[SUCESSO] Entidade 'alunos_2024' processada e salva no S3. Registros: 2120560

--- Iniciando processamento da entidade: alunos_2025 ---
[RAW] Baixando objeto do S3 via Boto3: raw/TS_ALUNO_2025.csv
[AVISO] Falha ao decodificar em UTF-8 para 'alunos_2025'. Tentando padrão ISO-8859-1 (Latin1)...
[RAW] Schema explícito encontrado para 'alunos_2025'. Ajustando tipos e tratando NaNs...
[BRONZE] Aplicando metadados de auditoria...
[BRONZE] Salvando Parquet temporariamente no Colab...
[S3-UPLOAD] Enviando arquivos Parquet para o S3 em: s3://fiap-datalake-fase2/bronze/alunos_2025/anomesdia=20260625/
[S3-UPLOAD] Upload concluído com sucesso!
[SUCESSO] Entidade 'alunos_2025' processada e salva no S3. Registros: 2222792

In [63]:
# ==============================================================================
# CAMADA SILVER - CÉLULA 1: DOWNLOAD MULTI-ENTIDADE DA BRONZE VIA BOTO3
# ==============================================================================
import os

# Configurações de diretórios globais da Silver
PASTA_SILVER = "silver"

print(f"--- [SILVER] Iniciando download em lote para as {len(ENTIDADES)} entidades ---")

# Loop para baixar os dados de todas as tabelas listadas na sua Bronze
for entidade in ENTIDADES:
    prefixo_s3_bronze = f"{PASTA_BRONZE}/{entidade}/anomesdia={ANOMESDIA}/"
    path_bronze_local = f"./output/{PASTA_BRONZE}/{entidade}/anomesdia={ANOMESDIA}/"

    print(f"\n📡 Buscando arquivos para '{entidade}' em: s3://{BUCKET_PRINICIPAL}/{prefixo_s3_bronze}")
    os.makedirs(path_bronze_local, exist_ok=True)

    try:
        response = s3_client.list_objects_v2(Bucket=BUCKET_PRINICIPAL, Prefix=prefixo_s3_bronze)

        if 'Contents' in response:
            for obj in response['Contents']:
                file_key = obj['Key']
                if file_key.endswith('/'):
                    continue

                nome_arquivo = os.path.basename(file_key)
                destino_local = os.path.join(path_bronze_local, nome_arquivo)

                print(f"  📥 Baixando Parquet: {nome_arquivo}...")
                s3_client.download_file(BUCKET_PRINICIPAL, file_key, destino_local)
        else:
            print(f"  ⚠️ Atenção: Nenhum arquivo encontrado para a entidade '{entidade}'.")
    except Exception as e:
        print(f"  ❌ Erro ao baixar dados de '{entidade}': {str(e)}")

print("\n✅ Processo de download em lote finalizado!")

--- [SILVER] Iniciando download em lote para as 8 entidades ---

📡 Buscando arquivos para 'meta_brasil' em: s3://fiap-datalake-fase2/bronze/meta_brasil/anomesdia=20260625/
  📥 Baixando Parquet: ._SUCCESS.crc...
  📥 Baixando Parquet: .part-00000-27c3da94-704a-47a4-9eb5-3b7b0bc75da9-c000.snappy.parquet.crc...
  📥 Baixando Parquet: .part-00001-27c3da94-704a-47a4-9eb5-3b7b0bc75da9-c000.snappy.parquet.crc...
  📥 Baixando Parquet: _SUCCESS...
  📥 Baixando Parquet: part-00000-27c3da94-704a-47a4-9eb5-3b7b0bc75da9-c000.snappy.parquet...
  📥 Baixando Parquet: part-00001-27c3da94-704a-47a4-9eb5-3b7b0bc75da9-c000.snappy.parquet...

📡 Buscando arquivos para 'meta_uf' em: s3://fiap-datalake-fase2/bronze/meta_uf/anomesdia=20260625/
  📥 Baixando Parquet: ._SUCCESS.crc...
  📥 Baixando Parquet: .part-00000-6a881ca0-d2f5-4c73-b260-9c052b4fa7ec-c000.snappy.parquet.crc...
  📥 Baixando Parquet: .part-00001-6a881ca0-d2f5-4c73-b260-9c052b4fa7ec-c000.snappy.parquet.crc...
  📥 Baixando Parquet: _SUCCESS...
  📥 Baixando Parquet: part-00000-6a881ca0-d2f5-4c73-b260-9c052b4fa7ec-c000.snappy.parquet...
  📥 Baixando Parquet: part-00001-6a881ca0-d2f5-4c73-b260-9c052b4fa7ec-c000.snappy.parquet...

📡 Buscando arquivos para 'meta_municipio' em: s3://fiap-datalake-fase2/bronze/meta_municipio/anomesdia=20260625/
  📥 Baixando Parquet: ._SUCCESS.crc...
  📥 Baixando Parquet: .part-00000-947926b1-22af-4a6b-abff-fdc787e3c7ec-c000.snappy.parquet.crc...
  📥 Baixando Parquet: .part-00001-947926b1-22af-4a6b-abff-fdc787e3c7ec-c000.snappy.parquet.crc...
  📥 Baixando Parquet: _SUCCESS...
  📥 Baixando Parquet: part-00000-947926b1-22af-4a6b-abff-fdc787e3c7ec-c000.snappy.parquet...
  📥 Baixando Parquet: part-00001-947926b1-22af-4a6b-abff-fdc787e3c7ec-c000.snappy.parquet...

📡 Buscando arquivos para 'municipio' em: s3://fiap-datalake-fase2/bronze/municipio/anomesdia=20260625/
  📥 Baixando Parquet: ._SUCCESS.crc...
  📥 Baixando Parquet: .part-00000-2ec258d9-0394-4a65-a23b-919d4a41099a-c000.snappy.parquet.crc...
  📥 Baixando Parquet: .part-00001-2ec258d9-0394-4a65-a23b-919d4a41099a-c000.snappy.parquet.crc...
  📥 Baixando Parquet: _SUCCESS...
  📥 Baixando Parquet: part-00000-2ec258d9-0394-4a65-a23b-919d4a41099a-c000.snappy.parquet...
  📥 Baixando Parquet: part-00001-2ec258d9-0394-4a65-a23b-919d4a41099a-c000.snappy.parquet...

📡 Buscando arquivos para 'uf' em: s3://fiap-datalake-fase2/bronze/uf/anomesdia=20260625/
  📥 Baixando Parquet: ._SUCCESS.crc...
  📥 Baixando Parquet: .part-00000-8cf4faeb-0a22-4145-9362-a006df8c7a25-c000.snappy.parquet.crc...
  📥 Baixando Parquet: .part-00001-8cf4faeb-0a22-4145-9362-a006df8c7a25-c000.snappy.parquet.crc...
  📥 Baixando Parquet: _SUCCESS...
  📥 Baixando Parquet: part-00000-8cf4faeb-0a22-4145-9362-a006df8c7a25-c000.snappy.parquet...
  📥 Baixando Parquet: part-00001-8cf4faeb-0a22-4145-9362-a006df8c7a25-c000.snappy.parquet...

📡 Buscando arquivos para 'alunos_2023' em: s3://fiap-datalake-fase2/bronze/alunos_2023/anomesdia=20260625/
  📥 Baixando Parquet: ._SUCCESS.crc...
  📥 Baixando Parquet: .part-00000-b533a25d-6270-4503-a132-caf2e2b7ea27-c000.snappy.parquet.crc...
  📥 Baixando Parquet: .part-00001-b533a25d-6270-4503-a132-caf2e2b7ea27-c000.snappy.parquet.crc...
  📥 Baixando Parquet: _SUCCESS...
  📥 Baixando Parquet: part-00000-b533a25d-6270-4503-a132-caf2e2b7ea27-c000.snappy.parquet...
  📥 Baixando Parquet: part-00001-b533a25d-6270-4503-a132-caf2e2b7ea27-c000.snappy.parquet...

📡 Buscando arquivos para 'alunos_2024' em: s3://fiap-datalake-fase2/bronze/alunos_2024/anomesdia=20260625/
  📥 Baixando Parquet: ._SUCCESS.crc...
  📥 Baixando Parquet: .part-00000-5740a601-6455-44a4-ac87-0266f27af1f1-c000.snappy.parquet.crc...
  📥 Baixando Parquet: .part-00001-5740a601-6455-44a4-ac87-0266f27af1f1-c000.snappy.parquet.crc...
  📥 Baixando Parquet: _SUCCESS...
  📥 Baixando Parquet: part-00000-5740a601-6455-44a4-ac87-0266f27af1f1-c000.snappy.parquet...
  📥 Baixando Parquet: part-00001-5740a601-6455-44a4-ac87-0266f27af1f1-c000.snappy.parquet...

📡 Buscando arquivos para 'alunos_2025' em: s3://fiap-datalake-fase2/bronze/alunos_2025/anomesdia=20260625/
  📥 Baixando Parquet: ._SUCCESS.crc...
  📥 Baixando Parquet: .part-00000-944491f9-b798-430f-a73e-ea85a7132fef-c000.snappy.parquet.crc...
  📥 Baixando Parquet: .part-00001-944491f9-b798-430f-a73e-ea85a7132fef-c000.snappy.parquet.crc...
  📥 Baixando Parquet: _SUCCESS...
  📥 Baixando Parquet: part-00000-944491f9-b798-430f-a73e-ea85a7132fef-c000.snappy.parquet...
  📥 Baixando Parquet: part-00001-944491f9-b798-430f-a73e-ea85a7132fef-c000.snappy.parquet...

✅ Processo de download em lote finalizado!

In [65]:
# ==============================================================================
# CAMADA SILVER - CÉLULA 2: TRATAMENTO DE VALORES NULOS E DUPLICIDADES EM LOTE
# ==============================================================================
from pyspark.sql import functions as F
from pyspark.sql.window import Window
import shutil
import os

print("--- [SILVER] Iniciando transformações e qualidade de dados ---")

# Dicionário dinâmico mapeando as chaves exclusivas de negócio baseadas nos schemas da Bronze
CHAVES_NEGOCIO_MAP = {
    "meta_brasil": ["ano", "rede"],
    "meta_uf": ["ano", "sigla_uf"],
    "meta_municipio": ["ano", "id_municipio"],
    "municipio": ["ano", "id_municipio"],
    "uf": ["ano", "sigla_uf"],
    "alunos_2023": ["NU_ANO_AVALIACAO", "ID_ALUNO"],
    "alunos_2024": ["NU_ANO_AVALIACAO", "ID_ALUNO"],
    "alunos_2025": ["NU_ANO_AVALIACAO", "ID_ALUNO"]
}

for entidade in ENTIDADES:
    print(f"\n🛠️ Processando qualidade da entidade: {entidade}")

    path_bronze_local = f"./output/{PASTA_BRONZE}/{entidade}/anomesdia={ANOMESDIA}/"
    path_silver_local = f"./output/{PASTA_SILVER}/{entidade}/anomesdia={ANOMESDIA}/"

    # Verifica se os arquivos da Bronze local realmente existem antes de ler
    if not os.path.exists(path_bronze_local) or not os.listdir(path_bronze_local):
        print(f"  ⏩ Pulando '{entidade}' pois não há arquivos locais baixados.")
        continue

    # 1. Leitura dos dados locais da Bronze
    df_raw = spark.read.parquet(path_bronze_local)
    total_inicial = df_raw.count()
    print(f"  📊 Registros originais na Bronze: {total_inicial}")

    # 2. Resgate dinâmico das colunas obrigatórias (chaves)
    colunas_obrigatorias = CHAVES_NEGOCIO_MAP.get(entidade)
    print(f"  🧹 Removendo nulos nas chaves: {colunas_obrigatorias}")
    df_silver = df_raw.dropna(subset=colunas_obrigatorias)

    # 3. Deduplicação por Window Function usando as chaves dinâmicas
    print("  ✨ Aplicando desduplicação por Window Function (Mais recente)...")
    window_spec = Window.partitionBy(*colunas_obrigatorias).orderBy(F.col("_ingestion_timestamp").desc())

    df_silver = (df_silver
        .withColumn("row_num", F.row_number().over(window_spec))
        .filter(F.col("row_num") == 1)
        .drop("row_num")
    )

    # ==========================================================================
    # REGRA ESPECÍFICA: TRATAMENTO DA TABELA ALUNOS 2025
    # ==========================================================================
    if entidade == "alunos_2025":
        colunas_para_dropar = [
            "CO_BLOCO_1", "TX_RESPOSTA_BLOCO_1", "TX_GABARITO_BLOCO_1",
            "CO_BLOCO_2", "TX_RESPOSTA_BLOCO_2", "TX_GABARITO_BLOCO_2",
            "CO_BLOCO_3", "TX_RESPOSTA_BLOCO_3", "TX_GABARITO_BLOCO_3",
            "CO_BLOCO_4", "TX_RESPOSTA_BLOCO_4", "TX_GABARITO_BLOCO_4"
        ]
        colunas_existentes_para_dropar = [c for c in colunas_para_dropar if c in df_silver.columns]

        if colunas_existentes_para_dropar:
            print(f"  🔥 [CUSTOM] Removendo {len(colunas_existentes_para_dropar)} colunas de blocos em alunos_2025")
            df_silver = df_silver.drop(*colunas_existentes_para_dropar)

        # Conversão de Float para Int (ID_ESCOLA, TP_DEPENDENCIA, CO_MUNICIPIO)
        print("  🔢 [CUSTOM] Convertendo colunas específicas para Inteiro...")
        colunas_para_inteiro = ["ID_ESCOLA", "TP_DEPENDENCIA", "CO_MUNICIPIO"]
        for col_num in colunas_para_inteiro:
            if col_num in df_silver.columns:
                df_silver = df_silver.withColumn(col_num, F.col(col_num).cast("int"))
    # ==========================================================================

    # 4. Padronização Condicional de Estados
    if "sigla_uf" in df_silver.columns:
        df_silver = df_silver.withColumn("sigla_uf", F.upper(F.trim(F.col("sigla_uf"))))
    elif "SG_UF" in df_silver.columns:
        df_silver = df_silver.withColumn("SG_UF", F.upper(F.trim(F.col("SG_UF"))))

    # --------------------------------------------------------------------------
    # TRATAMENTO 1: Substituir vazios/NaN por "Não identificado" em strings
    # --------------------------------------------------------------------------
    print("  ✍️ Substituindo valores nulos/vazios em colunas de texto...")
    colunas_string = [campo.name for campo in df_silver.schema.fields if campo.dataType.simpleString() == "string"]
    for col_name in colunas_string:
        df_silver = df_silver.withColumn(
            col_name,
            F.when(F.trim(F.col(col_name)) == "", F.lit(None)).otherwise(F.col(col_name))
        )
    df_silver = df_silver.fillna("Não identificado", subset=colunas_string)

    # --------------------------------------------------------------------------
    # TRATAMENTO 2: Arredondar colunas decimais para 2 casas em todas as tabelas
    # --------------------------------------------------------------------------
    colunas_decimais = [campo.name for campo in df_silver.schema.fields if campo.dataType.simpleString() in ["double", "float"]]

    if colunas_decimais:
        print(f"  📐 Arredondando {len(colunas_decimais)} coluna(s) decimal(ais) para 2 casas...")
        for col_dec in colunas_decimais:
            df_silver = df_silver.withColumn(col_dec, F.round(F.col(col_dec), 2))

    # --------------------------------------------------------------------------
    # Adição de Metadados Silver
    # --------------------------------------------------------------------------
    df_silver = (df_silver
        .withColumn("_silver_processed_at", F.current_timestamp())
        .withColumn("_pipeline_version", F.lit("v1.0_silver_glue"))
    )

    # 5. Escrita local temporária
    if os.path.exists(path_silver_local):
        shutil.rmtree(path_silver_local)

    print(f"  💾 Gravando arquivos Parquet em: {path_silver_local}")
    df_silver.write.mode("overwrite").parquet(path_silver_local)
    print(f"  ✅ Concluído! Registros finais na Silver: {df_silver.count()}")

print("\n🎉 Todas as tabelas foram tratadas e armazenadas localmente!")

--- [SILVER] Iniciando transformações e qualidade de dados ---

🛠️ Processando qualidade da entidade: meta_brasil
  📊 Registros originais na Bronze: 3
  🧹 Removendo nulos nas chaves: ['ano', 'rede']
  ✨ Aplicando desduplicação por Window Function (Mais recente)...
  ✍️ Substituindo valores nulos/vazios em colunas de texto...
  📐 Arredondando 9 coluna(s) decimal(ais) para 2 casas...
  💾 Gravando arquivos Parquet em: ./output/silver/meta_brasil/anomesdia=20260625/
  ✅ Concluído! Registros finais na Silver: 3

🛠️ Processando qualidade da entidade: meta_uf
  📊 Registros originais na Bronze: 54
  🧹 Removendo nulos nas chaves: ['ano', 'sigla_uf']
  ✨ Aplicando desduplicação por Window Function (Mais recente)...
  ✍️ Substituindo valores nulos/vazios em colunas de texto...
  📐 Arredondando 9 coluna(s) decimal(ais) para 2 casas...
  💾 Gravando arquivos Parquet em: ./output/silver/meta_uf/anomesdia=20260625/
  ✅ Concluído! Registros finais na Silver: 54

🛠️ Processando qualidade da entidade: meta_municipio
  📊 Registros originais na Bronze: 10704
  🧹 Removendo nulos nas chaves: ['ano', 'id_municipio']
  ✨ Aplicando desduplicação por Window Function (Mais recente)...
  ✍️ Substituindo valores nulos/vazios em colunas de texto...
  📐 Arredondando 10 coluna(s) decimal(ais) para 2 casas...
  💾 Gravando arquivos Parquet em: ./output/silver/meta_municipio/anomesdia=20260625/
  ✅ Concluído! Registros finais na Silver: 10704

🛠️ Processando qualidade da entidade: municipio
  📊 Registros originais na Bronze: 23995
  🧹 Removendo nulos nas chaves: ['ano', 'id_municipio']
  ✨ Aplicando desduplicação por Window Function (Mais recente)...
  ✍️ Substituindo valores nulos/vazios em colunas de texto...
  📐 Arredondando 11 coluna(s) decimal(ais) para 2 casas...
  💾 Gravando arquivos Parquet em: ./output/silver/municipio/anomesdia=20260625/
  ✅ Concluído! Registros finais na Silver: 11030

🛠️ Processando qualidade da entidade: uf
  📊 Registros originais na Bronze: 145
  🧹 Removendo nulos nas chaves: ['ano', 'sigla_uf']
  ✨ Aplicando desduplicação por Window Function (Mais recente)...
  ✍️ Substituindo valores nulos/vazios em colunas de texto...
  📐 Arredondando 11 coluna(s) decimal(ais) para 2 casas...
  💾 Gravando arquivos Parquet em: ./output/silver/uf/anomesdia=20260625/
  ✅ Concluído! Registros finais na Silver: 49

🛠️ Processando qualidade da entidade: alunos_2023
  📊 Registros originais na Bronze: 1747439
  🧹 Removendo nulos nas chaves: ['NU_ANO_AVALIACAO', 'ID_ALUNO']
  ✨ Aplicando desduplicação por Window Function (Mais recente)...
  ✍️ Substituindo valores nulos/vazios em colunas de texto...
  📐 Arredondando 2 coluna(s) decimal(ais) para 2 casas...
  💾 Gravando arquivos Parquet em: ./output/silver/alunos_2023/anomesdia=20260625/
  ✅ Concluído! Registros finais na Silver: 1747439

🛠️ Processando qualidade da entidade: alunos_2024
  📊 Registros originais na Bronze: 2120560
  🧹 Removendo nulos nas chaves: ['NU_ANO_AVALIACAO', 'ID_ALUNO']
  ✨ Aplicando desduplicação por Window Function (Mais recente)...
  ✍️ Substituindo valores nulos/vazios em colunas de texto...
  📐 Arredondando 2 coluna(s) decimal(ais) para 2 casas...
  💾 Gravando arquivos Parquet em: ./output/silver/alunos_2024/anomesdia=20260625/
  ✅ Concluído! Registros finais na Silver: 2120560

🛠️ Processando qualidade da entidade: alunos_2025
  📊 Registros originais na Bronze: 2222792
  🧹 Removendo nulos nas chaves: ['NU_ANO_AVALIACAO', 'ID_ALUNO']
  ✨ Aplicando desduplicação por Window Function (Mais recente)...
  🔢 [CUSTOM] Convertendo colunas específicas para Inteiro...
  ✍️ Substituindo valores nulos/vazios em colunas de texto...
  📐 Arredondando 2 coluna(s) decimal(ais) para 2 casas...
  💾 Gravando arquivos Parquet em: ./output/silver/alunos_2025/anomesdia=20260625/
  ✅ Concluído! Registros finais na Silver: 2222792

🎉 Todas as tabelas foram tratadas e armazenadas localmente!

In [66]:
# ==============================================================================
# CAMADA SILVER - CÉLULA 3: UPLOAD EM LOTE DOS DADOS TRATADOS PARA O S3 (SILVER)
# ==============================================================================

print("--- [SILVER] Iniciando upload em lote para a camada Silver no S3 ---")

for entidade in ENTIDADES:
    path_silver_local = f"./output/{PASTA_SILVER}/{entidade}/anomesdia={ANOMESDIA}/"
    key_s3_silver_output = f"{PASTA_SILVER}/{entidade}/anomesdia={ANOMESDIA}/"

    # Garante que só tentará subir se a pasta local foi criada no passo anterior
    if not os.path.exists(path_silver_local):
        continue

    print(f"\n🚀 Enviando '{entidade}' para: s3://{BUCKET_PRINICIPAL}/{key_s3_silver_output}/")

    try:
        fazer_upload_pasta_s3(
            pasta_local=path_silver_local,
            bucket=BUCKET_PRINICIPAL,
            prefixo_s3=key_s3_silver_output
        )
        print(f"  🎉 Upload de '{entidade}' concluído com sucesso!")
    except Exception as e:
        print(f"  ❌ Falha ao enviar arquivos de '{entidade}' para a Silver: {str(e)}")

print("\n🏆 Pipeline da Camada Silver finalizado com sucesso para todas as entidades!")

--- [SILVER] Iniciando upload em lote para a camada Silver no S3 ---

🚀 Enviando 'meta_brasil' para: s3://fiap-datalake-fase2/silver/meta_brasil/anomesdia=20260625//
  🎉 Upload de 'meta_brasil' concluído com sucesso!

🚀 Enviando 'meta_uf' para: s3://fiap-datalake-fase2/silver/meta_uf/anomesdia=20260625//
  🎉 Upload de 'meta_uf' concluído com sucesso!

🚀 Enviando 'meta_municipio' para: s3://fiap-datalake-fase2/silver/meta_municipio/anomesdia=20260625//
  🎉 Upload de 'meta_municipio' concluído com sucesso!

🚀 Enviando 'municipio' para: s3://fiap-datalake-fase2/silver/municipio/anomesdia=20260625//
  🎉 Upload de 'municipio' concluído com sucesso!

🚀 Enviando 'uf' para: s3://fiap-datalake-fase2/silver/uf/anomesdia=20260625//
  🎉 Upload de 'uf' concluído com sucesso!

🚀 Enviando 'alunos_2023' para: s3://fiap-datalake-fase2/silver/alunos_2023/anomesdia=20260625//
  🎉 Upload de 'alunos_2023' concluído com sucesso!

🚀 Enviando 'alunos_2024' para: s3://fiap-datalake-fase2/silver/alunos_2024/anomesdia=20260625//
  🎉 Upload de 'alunos_2024' concluído com sucesso!

🚀 Enviando 'alunos_2025' para: s3://fiap-datalake-fase2/silver/alunos_2025/anomesdia=20260625//
  🎉 Upload de 'alunos_2025' concluído com sucesso!

🏆 Pipeline da Camada Silver finalizado com sucesso para todas as entidades!

In [67]:
print("--- 🔍 VISUALIZANDO OS 3 PRIMEIROS REGISTROS DA CAMADA SILVER ---")

for entidade in CHAVES_NEGOCIO_MAP.keys():
    path_silver_local = f"./output/{PASTA_SILVER}/{entidade}/anomesdia={ANOMESDIA}/"

    if os.path.exists(path_silver_local) and os.listdir(path_silver_local):
        print(f"\n📊 Tabela: {entidade.upper()}")
        # Lê o Parquet da Silver e converte apenas o cabeçalho para Pandas
        df_preview = spark.read.parquet(path_silver_local).limit(3).toPandas()
        display(df_preview)
    else:
        print(f"\n⚠️ Tabela '{entidade}' não encontrada ou vazia no caminho local.")

--- 🔍 VISUALIZANDO OS 3 PRIMEIROS REGISTROS DA CAMADA SILVER ---

📊 Tabela: META_BRASIL

,ano,rede,taxa_alfabetizacao,meta_alfabetizacao_2024,meta_alfabetizacao_2025,meta_alfabetizacao_2026,meta_alfabetizacao_2027,meta_alfabetizacao_2028,meta_alfabetizacao_2029,meta_alfabetizacao_2030,percentual_participacao,_ingestion_timestamp,_ingestion_date,_source_path,_source_entity,_environment,_silver_processed_at,_pipeline_version
0,2023,Pública,55.9,59.9,63.77,67.47,70.97,74.23,77.24,80.0,86.00,20260625_025331,2026-06-25,s3://fiap-datalake-fase2/raw/br_inep_avaliacao...,meta_brasil,dev,2026-06-25 05:12:09.029614,v1.0_silver_glue
1,2024,Pública,59.2,59.9,63.77,67.47,70.97,74.23,77.24,80.0,87.37,20260625_025331,2026-06-25,s3://fiap-datalake-fase2/raw/br_inep_avaliacao...,meta_brasil,dev,2026-06-25 05:12:09.029614,v1.0_silver_glue
2,2025,Pública,66.0,60.0,64.00,67.00,71.00,74.00,77.00,80.0,88.00,20260625_025331,2026-06-25,s3://fiap-datalake-fase2/raw/br_inep_avaliacao...,meta_brasil,dev,2026-06-25 05:12:09.029614,v1.0_silver_glue

📊 Tabela: META_UF

,ano,sigla_uf,rede,taxa_alfabetizacao,meta_alfabetizacao_2024,meta_alfabetizacao_2025,meta_alfabetizacao_2026,meta_alfabetizacao_2027,meta_alfabetizacao_2028,meta_alfabetizacao_2029,meta_alfabetizacao_2030,percentual_participacao,_ingestion_timestamp,_ingestion_date,_source_path,_source_entity,_environment,_silver_processed_at,_pipeline_version
0,2023,AC,Pública,NaN,NaN,56.9,62.2,67.3,72.0,76.2,80.0,NaN,20260625_025331,2026-06-25,s3://fiap-datalake-fase2/raw/br_inep_avaliacao...,meta_uf,dev,2026-06-25 05:12:10.575871,v1.0_silver_glue
1,2023,AL,Pública,43.88,49.7,55.5,61.1,66.5,71.5,76.0,80.0,92.36,20260625_025331,2026-06-25,s3://fiap-datalake-fase2/raw/br_inep_avaliacao...,meta_uf,dev,2026-06-25 05:12:10.575871,v1.0_silver_glue
2,2023,AM,Pública,52.20,56.8,61.3,65.6,69.6,73.4,76.9,80.0,76.14,20260625_025331,2026-06-25,s3://fiap-datalake-fase2/raw/br_inep_avaliacao...,meta_uf,dev,2026-06-25 05:12:10.575871,v1.0_silver_glue

📊 Tabela: META_MUNICIPIO

,ano,id_municipio,rede,taxa_alfabetizacao,meta_alfabetizacao_2024,meta_alfabetizacao_2025,meta_alfabetizacao_2026,meta_alfabetizacao_2027,meta_alfabetizacao_2028,meta_alfabetizacao_2029,meta_alfabetizacao_2030,nivel_alfabetizacao,percentual_participacao,_ingestion_timestamp,_ingestion_date,_source_path,_source_entity,_environment,_silver_processed_at,_pipeline_version
0,2023,1100015,Municipal,64.6,67.08,69.51,71.84,74.06,76.16,78.14,80.0,3.0,89.37,20260625_025331,2026-06-25,s3://fiap-datalake-fase2/raw/br_inep_avaliacao...,meta_municipio,dev,2026-06-25 05:12:11.818499,v1.0_silver_glue
1,2023,1100023,Municipal,62.3,65.22,68.02,70.71,73.25,75.65,77.90,80.0,3.0,89.79,20260625_025331,2026-06-25,s3://fiap-datalake-fase2/raw/br_inep_avaliacao...,meta_municipio,dev,2026-06-25 05:12:11.818499,v1.0_silver_glue
2,2023,1100031,Municipal,69.1,70.85,72.53,74.15,75.71,77.21,78.64,80.0,3.0,90.48,20260625_025331,2026-06-25,s3://fiap-datalake-fase2/raw/br_inep_avaliacao...,meta_municipio,dev,2026-06-25 05:12:11.818499,v1.0_silver_glue

📊 Tabela: MUNICIPIO

,ano,id_municipio,serie,rede,taxa_alfabetizacao,media_portugues,proporcao_aluno_nivel_0,proporcao_aluno_nivel_1,proporcao_aluno_nivel_2,proporcao_aluno_nivel_3,...,proporcao_aluno_nivel_6,proporcao_aluno_nivel_7,proporcao_aluno_nivel_8,_ingestion_timestamp,_ingestion_date,_source_path,_source_entity,_environment,_silver_processed_at,_pipeline_version
0,2023,1100015,2,3,64.55,758.33,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,20260625_025331,2026-06-25,s3://fiap-datalake-fase2/raw/br_inep_avaliacao...,municipio,dev,2026-06-25 05:12:13.480618,v1.0_silver_glue
1,2023,1100023,2,5,62.30,757.10,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,20260625_025331,2026-06-25,s3://fiap-datalake-fase2/raw/br_inep_avaliacao...,municipio,dev,2026-06-25 05:12:13.480618,v1.0_silver_glue
2,2023,1100031,2,3,69.10,767.88,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,20260625_025331,2026-06-25,s3://fiap-datalake-fase2/raw/br_inep_avaliacao...,municipio,dev,2026-06-25 05:12:13.480618,v1.0_silver_glue

📊 Tabela: UF

,ano,sigla_uf,serie,rede,taxa_alfabetizacao,media_portugues,proporcao_aluno_nivel_0,proporcao_aluno_nivel_1,proporcao_aluno_nivel_2,proporcao_aluno_nivel_3,...,proporcao_aluno_nivel_6,proporcao_aluno_nivel_7,proporcao_aluno_nivel_8,_ingestion_timestamp,_ingestion_date,_source_path,_source_entity,_environment,_silver_processed_at,_pipeline_version
0,2023,AL,2,5,43.88,729.72,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,20260625_025331,2026-06-25,s3://fiap-datalake-fase2/raw/br_inep_avaliacao...,uf,dev,2026-06-25 05:12:15.774121,v1.0_silver_glue
1,2023,AM,2,3,49.20,733.66,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,20260625_025331,2026-06-25,s3://fiap-datalake-fase2/raw/br_inep_avaliacao...,uf,dev,2026-06-25 05:12:15.774121,v1.0_silver_glue
2,2023,AP,2,3,41.87,732.79,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,20260625_025331,2026-06-25,s3://fiap-datalake-fase2/raw/br_inep_avaliacao...,uf,dev,2026-06-25 05:12:15.774121,v1.0_silver_glue

📊 Tabela: ALUNOS_2023

,NU_ANO_AVALIACAO,CO_UF,SG_UF,ID_ALUNO,TP_SERIE,ID_ESCOLA,TP_DEPENDENCIA,CO_MUNICIPIO,NO_MUNICIPIO,IN_PRESENCA_LP,...,VL_PESO_ALUNO_LP,VL_PROFICIENCIA_LP,IN_ALFABETIZADO,_ingestion_timestamp,_ingestion_date,_source_path,_source_entity,_environment,_silver_processed_at,_pipeline_version
0,2023,11,RO,11000003,2,60000062,3,1100023,Ariquemes,1,...,1.06,790.36,1,20260625_025331,2026-06-25,s3://fiap-datalake-fase2/raw/TS_ALUNO_2023.csv,alunos_2023,dev,2026-06-25 05:12:17.373255,v1.0_silver_glue
1,2023,11,RO,11000006,2,60000062,3,1100023,Ariquemes,1,...,1.06,790.03,1,20260625_025331,2026-06-25,s3://fiap-datalake-fase2/raw/TS_ALUNO_2023.csv,alunos_2023,dev,2026-06-25 05:12:17.373255,v1.0_silver_glue
2,2023,11,RO,11000007,2,60000062,3,1100023,Ariquemes,1,...,1.06,759.09,1,20260625_025331,2026-06-25,s3://fiap-datalake-fase2/raw/TS_ALUNO_2023.csv,alunos_2023,dev,2026-06-25 05:12:17.373255,v1.0_silver_glue

📊 Tabela: ALUNOS_2024

,NU_ANO_AVALIACAO,CO_UF,SG_UF,ID_ALUNO,TP_SERIE,ID_ESCOLA,TP_DEPENDENCIA,CO_MUNICIPIO,NO_MUNICIPIO,IN_PRESENCA_LP,...,VL_PESO_ALUNO_LP,VL_PROFICIENCIA_LP,IN_ALFABETIZADO,_ingestion_timestamp,_ingestion_date,_source_path,_source_entity,_environment,_silver_processed_at,_pipeline_version
0,2024,11,RO,11000004,2,60000062,3,1100023,Ariquemes,1,...,1.06,675.40,0,20260625_025331,2026-06-25,s3://fiap-datalake-fase2/raw/TS_ALUNO_2024.csv,alunos_2024,dev,2026-06-25 05:12:47.910410,v1.0_silver_glue
1,2024,11,RO,11000005,2,60000062,3,1100023,Ariquemes,1,...,1.06,747.62,1,20260625_025331,2026-06-25,s3://fiap-datalake-fase2/raw/TS_ALUNO_2024.csv,alunos_2024,dev,2026-06-25 05:12:47.910410,v1.0_silver_glue
2,2024,11,RO,11000007,2,60000062,3,1100023,Ariquemes,1,...,1.06,740.54,0,20260625_025331,2026-06-25,s3://fiap-datalake-fase2/raw/TS_ALUNO_2024.csv,alunos_2024,dev,2026-06-25 05:12:47.910410,v1.0_silver_glue

📊 Tabela: ALUNOS_2025

,NU_ANO_AVALIACAO,CO_UF,SG_UF,ID_ALUNO,TP_SERIE,ID_ESCOLA,TP_DEPENDENCIA,CO_MUNICIPIO,NO_MUNICIPIO,IN_PRESENCA_LP,...,VL_PESO_ALUNO_LP,VL_PROFICIENCIA_LP,IN_ALFABETIZADO,_ingestion_timestamp,_ingestion_date,_source_path,_source_entity,_environment,_silver_processed_at,_pipeline_version
0,2025,11,RO,11000677,2,60000060,3,1100023,Ariquemes,1,...,1.5,781.78,1,20260625_025331,2026-06-25,s3://fiap-datalake-fase2/raw/TS_ALUNO_2025.csv,alunos_2025,dev,2026-06-25 05:13:24.735354,v1.0_silver_glue
1,2025,11,RO,11000678,2,60000060,3,1100023,Ariquemes,1,...,1.5,717.88,0,20260625_025331,2026-06-25,s3://fiap-datalake-fase2/raw/TS_ALUNO_2025.csv,alunos_2025,dev,2026-06-25 05:13:24.735354,v1.0_silver_glue
2,2025,11,RO,11000679,2,60000060,3,1100023,Ariquemes,1,...,1.5,657.84,0,20260625_025331,2026-06-25,s3://fiap-datalake-fase2/raw/TS_ALUNO_2025.csv,alunos_2025,dev,2026-06-25 05:13:24.735354,v1.0_silver_glue